sonar.projectKey=boinar_sovlens
sonar.organization=boinar
sonar.sources=src
sonar.exclusions=**/*.spec.ts,**/node_modules/**,**/dist/**,**/coverage/**
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.tsconfigPath=tsconfig.json