global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'sovlens-backend'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['backend:4000']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'garage-vps'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['garage:3903']

  - job_name: 'garage-homelab'
    metrics_path: '/metrics'
    authorization:
      credentials_file: '/etc/prometheus/secrets/garage_homelab_token'
    static_configs:
      - targets: ['192.168.1.20:3903']